Efes.Backoffice/Controllers/ProtocolController.cs
using System;
using System.Web.Mvc;
using Efes.Entities.Protocol;
using Efes.UIPC;
using Efes.Utility;
using Efes.WC;

namespace Efes.Backoffice.Controllers
{
    [AuthorizeMember]
    public class ProtocolController : BaseController
    {
        private readonly ProtocolUipc _protocolUipc;
        public ProtocolController()
        {
            _protocolUipc = new ProtocolUipc();
        }

        [AuthorizeMember(Rules ="ViewProtocolViewList")]
        public ActionResult Index()
        {
            var model = _protocolUipc.GetProtocolApprovements(Authentication.UserInfo.Id);
            return View(model);
        }

        [AuthorizeMember(Rules ="ApproveWaitingProtocol")]
        public ActionResult Approve(string protocolId)
        {
            var result = _protocolUipc.ApproveProtocol(protocolId.Convert<int>(), Authentication.UserInfo.Id);
            if (result)
            {
                this.ViewBag.Message = "Kayıt başarıyla onaylandı.";
                this.ViewBag.MessageType = "success";
            }
            else
            {
                this.ViewBag.Message = "Kayıt onaylanirken hata oluştu.";
                this.ViewBag.MessageType = "success";
            }
            ModelState.AddModelError("", "Already outbid");
            return RedirectToAction("Index");
        }

        [AuthorizeMember(Rules ="CancelWaitingProtocol")]
        public ActionResult Cancel(string protocolId)
        {
            var result = _protocolUipc.CancelProtocol(protocolId.Convert<int>(), Authentication.UserInfo.Id);
            if (result)
            {
                this.ViewBag.Message = "Kayıt başarıyla iptal edildi.";
                this.ViewBag.MessageType = "success";
            }
            else
            {
                this.ViewBag.Message = "Kayıt iptal edilirken hata oluştu.";
                this.ViewBag.MessageType = "success";
            }
            return RedirectToAction("Index");
        }

        [AuthorizeMember(Rules = "DailyProtocolList")]
        public ActionResult DailyProtocolList()
        {
            var model = _protocolUipc.DailyProtocolList(Authentication.UserInfo.Id);
            return View(model);
        }

        [AuthorizeMember(Rules = "InsertPaymentPromise")]
        public ActionResult InsertPaymentPromise(PaymentPromise paymentPromise)
        {
            paymentPromise.UserId = Authentication.UserInfo.Id;
            var result = _protocolUipc.InsertPaymentPromise(paymentPromise);
            return Json(new { isSuccess = result });
        }

        [AuthorizeMember(Rules = "CancelPaymentPromise|CancelOwnPaymentPromise")]
        public ActionResult CancelPaymentPromise(string promiseId)
        {
            var result = _protocolUipc.CancelPaymentPromise(Authentication.UserInfo.Id, promiseId.Convert<int>());
            return Json(new { isSuccess = result });
        }

        [AuthorizeMember(Rules = "ViewPaymentPromiseList")]
        public ActionResult PaymentPromiseList(string startDate, string endDate)
        {
            DateTime sDate;
            DateTime eDate;
            if (string.IsNullOrWhiteSpace(startDate) || string.IsNullOrWhiteSpace(endDate))
            {
                sDate = DateTime.Now.AddDays(-7);
                eDate = DateTime.Now;
            }
            else
            {
                sDate = startDate.Convert<DateTime>();
                eDate = endDate.Convert<DateTime>();

                if (sDate == default(DateTime) || eDate == default(DateTime))
                {
                    sDate = DateTime.Now.AddDays(-7);
                    eDate = DateTime.Now;
                }
            }

            ViewBag.SDate = sDate.ToString("dd-MM-yyyy");
            ViewBag.EDate = eDate.ToString("dd-MM-yyyy");

            var model = _protocolUipc.GetPaymentPromiseReport(Authentication.UserInfo.Id, sDate, eDate);
            return View(model);
        }
    }
}

Efes.Backoffice/Views/Protocol/DailyProtocolList.cshtml
@model IEnumerable<Efes.Models.ProtocolListModel>

@{
    ViewBag.Title = "Günlük Protokol Listesi";
}

<div class="row">
    <div class="col-md-12" id="fileUploadDiv">
        <div class="portlet light portlet-fit bordered" id="blockPlace">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-blue-sharp sbold">Günlük Protokol Listesi</span>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="approvementListTable" style="display: none;">
                    <thead>
                        <tr>
                            <th> Account Id </th>
                            <th> Protokol Id</th>
                            <th> Ad Soyad</th>
                            <th> Yaş</th>
                            <th> Kişi Tipi</th>
                            <th> Gönderen </th>
                            <th> Anapara </th>
                            <th> Toplam Risk </th>
                            <th> Tutar </th>
                            <th> Taksit Sayısı</th>
                            <th> Tarih</th>
                            <th> Kapama Oranı </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var prt in Model)
                            {
                                <tr data-id="@prt.Id">
                                    <td><a href="/Obligor/Detail?accountId=@(prt.Id)" target="_blank">@prt.Id</a></td>
                                    <td>@prt.ProtocolId</td>
                                    <td>@prt.NameSurname</td>
                                    <td>@prt.ObligorAge</td>
                                    <td>@prt.Relation</td>
                                    <td>@prt.CreatedBy</td>
                                    <td>@(prt.DebtPrinciple) TL</td>
                                    <td>@(prt.TotalDebtAmount) TL</td>
                                    <td>@prt.PlanAmount</td>
                                    <td>@prt.InstallmentCount</td>
                                    <td>@prt.CreateDate.ToShortDateString()</td>
                                    <td>
                                        <div class="easy-pie-chart @prt.Colour">
                                            <div class="number transactions" data-percent="@((int)(((prt.PlanAmount + prt.TotalCreditAmount)/prt.DebtPrinciple)* 100))">
                                                %<span>@((int)(((prt.PlanAmount + prt.TotalCreditAmount) / prt.DebtPrinciple) * 100))</span>
                                            </div>
                                            <a class="title" href="javascript:;">
                                                @(prt.PlanAmount + prt.TotalCreditAmount) TL / @(prt.DebtPrinciple) TL
                                            </a>
                                        </div>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@Html.ValidationSummary()

@section PageScripts{
    @Scripts.Render("~/bundles/dashboard")


    <script type="text/javascript">
        $(function () {
            $(".easy-pie-chart.yellow .number.transactions").easyPieChart({
                animate: 2000,
                size: 75,
                lineWidth: 3,
                barColor: App.getBrandColor("yellow")
            });
            $(".easy-pie-chart.green .number.transactions").easyPieChart({
                animate: 2000,
                size: 75,
                lineWidth: 3,
                barColor: App.getBrandColor("green")
            });
            $(".easy-pie-chart.red .number.transactions").easyPieChart({
                animate: 2000,
                size: 75,
                lineWidth: 3,
                barColor: App.getBrandColor("red")
            });

            $("#approvementListTable").dataTable($.extend(CommonDataTablesSettings, { "order": [[1, "desc"]] })).show();

            @if (!string.IsNullOrWhiteSpace(this.ViewBag.Message) && !string.IsNullOrWhiteSpace(this.ViewBag.MessageType))
            {
                <text>
            Message.Show("@(this.ViewBag.Message)", "@(this.ViewBag.MessageType == "success" ? "Bilgilendirme" : "Hata")", @(this.ViewBag.MessageType == "success" ? "Message.ThemeType.Teal" : "Message.ThemeType.Ruby"));
            </text>
            }
        });

    </script>
}

Efes.Backoffice/Views/Protocol/Index.cshtml
@using Efes.WC
@model IEnumerable<Efes.Models.ProtocolApprovementModel>

@{
    ViewBag.Title = "Protokol";
}


<div class="row">
    <div class="col-md-12" id="fileUploadDiv">
        <div class="portlet light portlet-fit bordered" id="blockPlace">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-blue-sharp sbold">Onay Bekleyen Protokoller</span>
                </div>
            </div>
            <div class="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="approvementListTable" style="display: none;">
                    <thead>
                        <tr>
                            <th> Account Id </th>
                            <th> Protokol Id</th>
                            <th> Ad Soyad</th>
                            <th> Yaş</th>
                            <th> Kişi Tipi</th>
                            <th> Gönderen </th>
                            <th> Anapara </th>
                            <th> Toplam Risk </th>
                            <th> Tutar </th>
                            <th> Taksit Sayısı</th>
                            <th> Tarih</th>
                            <th> Kapama Oranı </th>
                            @if (Authentication.IsAllowedToSee("ApproveWaitingProtocol"))
                            {
                                <th> </th>
                            }
                            @if (Authentication.IsAllowedToSee("CancelWaitingProtocol"))
                            {
                                <th> </th>
                            }
                            <th> İşlemler </th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var prt in Model)
                            {
                                <tr data-id="@prt.Id">
                                    <td><a href="/Obligor/Detail?accountId=@(prt.Id)" target="_blank">@prt.Id</a></td>
                                    <td>@prt.ProtocolId</td>
                                    <td>@prt.NameSurname</td>
                                    <td>@prt.ObligorAge</td>
                                    <td>@prt.Relation</td>
                                    <td>@prt.CreatedBy</td>
                                    <td>@(prt.DebtPrinciple) TL</td>
                                    <td>@(prt.TotalDebtAmount) TL</td>
                                    <td>@prt.PlanAmount</td>
                                    <td>@prt.InstallmentCount</td>
                                    <td>@prt.CreateDate.ToShortDateString()</td>
                                    <td>
                                        <div class="easy-pie-chart @prt.Colour">
                                            <div class="number transactions" data-percent="@((int)(((prt.PlanAmount + prt.TotalCreditAmount)/prt.DebtPrinciple)* 100))">
                                                %<span>@((int)(((prt.PlanAmount + prt.TotalCreditAmount) / prt.DebtPrinciple) * 100))</span>
                                            </div>
                                            <a class="title" href="javascript:;">
                                                @(prt.PlanAmount + prt.TotalCreditAmount) TL / @(prt.DebtPrinciple) TL
                                            </a>
                                        </div>
                                    </td>
                                    @if (Authentication.IsAllowedToSee("ApproveWaitingProtocol"))
                                    {
                                        <td>
                                            @using (Html.BeginForm("Approve", "Protocol", FormMethod.Post))
                                            {
                                                <input type="hidden" name="protocolId" value="@prt.ProtocolId" />
                                                <button class="btn btn-success" name="Approve">Onayla</button>
                                            }
                                        </td>
                                    }
                                    @if (Authentication.IsAllowedToSee("CancelWaitingProtocol"))
                                    {
                                        <td>
                                            @using (Html.BeginForm("Cancel", "Protocol", FormMethod.Post))
                                            {
                                                <input type="hidden" name="protocolId" value="@prt.ProtocolId" />
                                                <button class="btn btn-danger">İptal Et</button>
                                            }
                                        </td>
                                    }
                                    <td>
                                        @if (!string.IsNullOrWhiteSpace(prt.GkfUrl))
                                        {
                                            <a href="@prt.GkfUrl" target="_blank" class="btn blue btn-block">GKF'yi Görüntüle</a>
                                        }
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>

@Html.ValidationSummary()

@section PageScripts{
    @Scripts.Render("~/bundles/dashboard")


    <script type="text/javascript">
        $(function () {
            $(".easy-pie-chart.yellow .number.transactions").easyPieChart({
                animate: 2000,
                size: 75,
                lineWidth: 3,
                barColor: App.getBrandColor("yellow")
            });
            $(".easy-pie-chart.green .number.transactions").easyPieChart({
                animate: 2000,
                size: 75,
                lineWidth: 3,
                barColor: App.getBrandColor("green")
            });
            $(".easy-pie-chart.red .number.transactions").easyPieChart({
                animate: 2000,
                size: 75,
                lineWidth: 3,
                barColor: App.getBrandColor("red")
            });

            $("#approvementListTable").dataTable($.extend(CommonDataTablesSettings, { "order": [[1, "desc"]] })).show();

            @if (!string.IsNullOrWhiteSpace(this.ViewBag.Message) && !string.IsNullOrWhiteSpace(this.ViewBag.MessageType))
            {
                <text>
            Message.Show("@(this.ViewBag.Message)", "@(this.ViewBag.MessageType == "success" ? "Bilgilendirme" : "Hata")", @(this.ViewBag.MessageType == "success" ? "Message.ThemeType.Teal" : "Message.ThemeType.Ruby"));
            </text>
            }
        });

    </script>
}

Efes.Backoffice/Views/Protocol/PaymentPromiseList.cshtml
@using Efes.WC
@model  List<Efes.Entities.Protocol.PaymentPromise>
@{
    ViewBag.Title = "Ödeme Sözü Listesi";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-blue-sharp sbold">Ödeme Sözü Listesi</span>
                </div>
            </div>
            <div class="portlet-body">
                <div class="row" style="margin-bottom: 10px;">
                    <label class="control-label col-md-1">Başlangıç Tarihi</label>

                    <div class="col-md-3">
                        <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy">
                            <input type="text" class="form-control" readonly name="dateTime" id="txtStartDate" value="@ViewBag.SDate">
                            <span class="input-group-btn">
                                <button class="btn default" type="button">
                                    <i class="fa fa-calendar"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
                <div class="row" style="margin-bottom: 10px;">
                    <label class="control-label col-md-1">Bitiş Tarihi</label>

                    <div class="col-md-3">
                        <div class="input-group input-medium date date-picker" data-date-format="dd-mm-yyyy">
                            <input type="text" class="form-control" readonly name="dateTime" id="txtEndDate" value="@ViewBag.EDate">
                            <span class="input-group-btn">
                                <button class="btn default" type="button">
                                    <i class="fa fa-calendar"></i>
                                </button>
                            </span>
                        </div>
                    </div>

                </div>
                <div class="row col-md-4" style="margin-bottom: 10px;">

                    <div class="col-md-2">
                        <button class="btn btn-sm blue btn-block col-md-1" type="button" onclick="GetData()">
                            Ara
                        </button>
                    </div>
                </div>

                @if (Model.Any())
                {
                    <div id="tablePromiseList">
                        <table class="table table-striped table-bordered table-hover tablePager">
                            <thead>
                                <tr>
                                    <th> Account Id </th>
                                    <th> İsim </th>
                                    <th> Plan Tutarı </th>
                                    <th> Peşinat </th>
                                    <th> Taksit Sayısı </th>
                                    <th> Söz Tarihi </th>
                                    <th> Oluşturulma Tarihi </th>
                                    <th> İşlemler </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr data-row-id="@item.Id">
                                        <td><a href="/Obligor/Detail?accountId=@item.AccountId">@item.AccountId</a></td>
                                        <td>@item.Name</td>
                                        <td>@item.PlanAmount</td>
                                        <td>@item.AdvancePayment</td>
                                        <td>@item.InstallmentCount</td>
                                        <td>@item.Date </td>
                                        <td>@item.CreateDate</td>
                                        <th>
                                            @if (Authentication.IsAllowedToSee("CancelPaymentPromise")
                                                || (Authentication.IsAllowedToSee("CancelOwnPaymentPromise")
                                                && item.Name == Authentication.UserInfo.Name))
                                            {
                                                <button class="btn btn-sm blue btn-block" type="button"
                                                        onclick="Cancel('@item.Id')">
                                                    İptal Et
                                                </button>
                                            }
                                        </th>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                }
            </div>


            @if (!Model.Any())
            {
                <div class="alert alert-info margin-top-40  ">
                    <strong>Bilgi!</strong> Ödeme sözü bulunamadı.
                </div>
            }
        </div>
    </div>
</div>
@section PageScripts{

    <script type="text/javascript">
        $(".tablePager").dataTable(
            $.extend(CommonDataTablesSettings,
                {
                    "order": [[4, "desc"]],
                    "pageLength": 20,
                    buttons: [
                        {
                            extend: 'excel',
                            exportOptions: {
                                modifier: {
                                    // DataTables core
                                    order: 'index', // 'current', 'applied',
                                    //'index', 'original'
                                    page: 'all', // 'all', 'current'
                                    search: 'none' // 'none', 'applied', 'removed'
                                },
                                columns: [0, 1, 2, 3, 4, 5, 6]
                            }
                        }
                    ]
                })
        );
        var GetData = function () {
            var sdate = $("#txtStartDate").val();
            var edate = $("#txtEndDate").val();
            location.href = "/Protocol/PaymentPromiseList?startDate=" + sdate + "&endDate=" + edate;
        }

        var Cancel = function (promiseId) {
            Core.AjaxCall({
                url: "/Protocol/CancelPaymentPromise",
                data: JSON.stringify(
                    {
                        promiseId: promiseId
                    }),
                success: function (response) {
                    if (response.isSuccess) {
                        $("tr[data-row-id='" + promiseId + "']").remove();
                        if ($(".pager tr").length === 0) {
                            $("#tablePromiseList")
                                .html(
                                '<div class="alert alert-info margin-top-40"><strong>Bilgi!</strong> Ödeme sözü bulunamadı.</div>');
                        }
                    } else {
                        alert("Hata oluştu !!");
                    }
                }
            });
        }
    </script>
}