Efes.Backoffice/Controllers/SmartCallingController.cs
using System;
using Efes.WC;
using Efes.UIPC;
using Efes.Models;
using System.Data;
using System.Linq;
using Efes.Utility;
using System.Web.Mvc;
using Newtonsoft.Json;
using Efes.Entities.Fgs;
using Efes.Entities.User;
using Efes.Entities.SmartCalling;
using System.Collections.Generic;
using Efes.Models.SmartCalling;

namespace Efes.Backoffice.Controllers
{
    //[AuthorizeMember(Rules = "SmartCalling")]
    public class SmartCallingController : Controller
    {
        private readonly SmartCallingUipc _smartCallingUipc;
        private readonly FgsUipc _fgsUipc;
        private readonly ReminderUipc _reminderUipc;
        private readonly UserUipc _userUipc;

        public SmartCallingController()
        {
            _smartCallingUipc = new SmartCallingUipc();
            _fgsUipc = new FgsUipc();
            _reminderUipc = new ReminderUipc();
            _userUipc = new UserUipc();
        }

        public ActionResult TodayPayments()
        {
            var model = _smartCallingUipc.GetTodayPaymentsList(Authentication.UserInfo.Id);
            return View(model);
        }

        public ActionResult NewAppointed(string type)
        {
            var model = _smartCallingUipc.GetNewAppointedList(Authentication.UserInfo.Id, type.Convert<int>());
            return View(model);
        }

        public ActionResult CancelProtocol()
        {
            var model = _smartCallingUipc.GetCancelProtocolList(Authentication.UserInfo.Id);
            return View(model);
        }

        public ActionResult ByCapitalGroup(int debtGroupType = 0, int portfolioId = 0)
        {
            var debtGroups = _smartCallingUipc.GetDebtGroup(Authentication.UserInfo.Id);
            int firstDebtGroup = debtGroups.Any() ? debtGroups.First().Key.Convert<int>() : 0;
            if (debtGroupType == 0 && firstDebtGroup != 0)
            {
                debtGroupType = firstDebtGroup;
            }

            var model = _smartCallingUipc.GetByCapitalGroupList(Authentication.UserInfo.Id, debtGroupType, portfolioId);
            model.SelectedDebtGroup = debtGroupType;
            model.SelectedPortfolio = portfolioId;

            return View(model);
        }

        public ActionResult CollectionWithoutProtocol()
        {
            var model = _smartCallingUipc.GetCollectionWithoutProtocolList(Authentication.UserInfo.Id);
            return View(model);
        }

        public ActionResult Expired()
        {
            var model = _smartCallingUipc.GetExpiredList(Authentication.UserInfo.Id);
            return View(model);
        }

        [HttpPost]
        [AuthorizeMember(Rules = "MakeCall")]
        public ActionResult CallWithList(string callList)
        {
            var calls = JsonConvert.DeserializeObject<List<ClientCallDetail>>(callList);
            var serverList = new List<Call>();

            if (calls.Any())
            {
                serverList.AddRange(calls.Select(call => new Call
                {
                    TelNo = call.Phone,
                    Cpn = string.IsNullOrWhiteSpace(call.Cpn) ? Authentication.UserInfo.PhoneNumber : call.Cpn,
                    AgentName = Authentication.UserInfo.LoginName,
                    QueueNo = 0,
                    RecordType = Call.RecordTypeEnum.Pool,
                    NextTryDate = new DateTime(2001, 1, 1),
                    CustomerName = call.Name,
                    CompanyName = "",
                    AccountId = call.AccountId
                }));

                if (serverList.Any())
                {
                    foreach (var call in serverList)
                    {
                        _fgsUipc.Call(call);
                    }
                    return Json(new { isSuccess = true });
                }
            }

            return Json(new { isSuccess = false });
        }

        public ActionResult CallOne(string number, string preferredCpn = "", string customerName = "", string companyName = "", string accountId = "")
        {
            var call = new Call
            {
                TelNo = number,
                Cpn = string.IsNullOrWhiteSpace(preferredCpn.Trim()) ? Authentication.UserInfo.PhoneNumber : preferredCpn,
                //AgentName = "agent1",
                AgentName = Authentication.UserInfo.LoginName,
                QueueNo = 0,
                RecordType = Call.RecordTypeEnum.Agent,
                NextTryDate = new DateTime(2001, 1, 1),
                CustomerName = customerName,
                CompanyName = companyName,
                AccountId = accountId
            };
            //call.AgentName = Authentication.UserInfo.LoginName;

            var resultId = _fgsUipc.Call(call);
            return Json(new { isSuccess = resultId > 0, resultId = resultId });
        }

        public ActionResult Reminder(string date = "")
        {
            DateTime tDate = string.IsNullOrEmpty(date) ? DateTime.Now : date.Convert<DateTime>();

            var model = _reminderUipc.GetReminderByUserId(Authentication.UserInfo.Id, tDate);
            ViewBag.Date = tDate.ToString("dd-MM-yyyy");
            return View(model);
        }

        [HttpGet]
        [AuthorizeMember(Rules = "CreateDialer")]
        public ActionResult CreateDialer()
        {
            var model = new CreateDialerModel { DialerStatus = _smartCallingUipc.GetCurrentDialerStatus() };

            //Sadece sayet Dialer kullanimda yada duraklatilmis degilse 
            //Yani dialer olusturmaya uygunsa agent listesi cagrilmistir.
            if (model.DialerStatus == DialerStatus.Passive)
            {
                model.UnselectedUsers = _userUipc.GetUsersHasOnlyOneRoleByRoleRoleId(Roles.TahsilatYetkilisi);
            }

            return View(model);
        }

        [HttpPost]
        [AuthorizeMember(Rules = "CreateDialer")]
        public ActionResult InsertExcel()
        {
            const string cacheName = "Dialer";
            //Eger dosya yoksa hata don
            if (Request.Files.Count == 0)
            {
                return Json(new { Result = "Error", Message = "File is missing." }, JsonRequestBehavior.AllowGet);
            }

            var necessaryColumnList = new List<string>() { "AccountId", "PhoneNumber" };

            var resultList = ExcelHelper.ExcelImport(necessaryColumnList, Request, Authentication.UserInfo.Id, cacheName);
            if (resultList.Any())
            {
                return Json(new { Result = "Error", MissingColumnNames = string.Join(",", resultList) });
            }

            var dt = CacheManager.Default.Get(cacheName + Request.BoUniqueId()) as DataTable;
            if (dt.HasData())
            {
                if (dt != null)
                {
                    var tempList = (dt.Columns.Cast<DataColumn>()
                        .Where(column => !necessaryColumnList.Contains(column.ColumnName.Trim()))
                        .Select(column => column.ColumnName)).ToList();

                    foreach (var columnname in tempList)
                    {
                        dt.Columns.Remove(columnname);
                    }
                }

                return Json(new { Result = "Success", AccountIdList = (dt.ToStringListTwoColumns("AccountId", "PhoneNumber", "|")) });
            }

            CacheManager.Default.Remove(cacheName + Request.BoUniqueId());
            return Json(true ? new { Result = "Success" } : new { Result = "Error", });
        }

        [HttpPost]
        [AuthorizeMember(Rules = "CreateDialer")]
        public ActionResult StartDialer(List<string> selectedAgents, 
                                        List<string> loadedAccounts, 
                                        string bandwidth, 
                                        string maxWaitingTime,
                                        string useFct)
        {
            var dtAgents = Utilities.GetNewdatatable(
                new Dictionary<string, string>
                {
                    { "Agent", "System.String" }
                });

            foreach (var pDetail in selectedAgents)
            {
                var dr = dtAgents.NewRow();
                dr["Agent"] = pDetail;
                dtAgents.Rows.Add(dr);
            }

            var dtAccounts = Utilities.GetNewdatatable(
                new Dictionary<string, string>
                {
                    { "AccountId", "System.String" },
                    { "PhoneNumber", "System.String" }
                });

            foreach (var pDetail in loadedAccounts)
            {
                var dr = dtAccounts.NewRow();
                dr["AccountId"] = pDetail.Split('|')[0];
                dr["PhoneNumber"] = pDetail.Split('|')[1];
                dtAccounts.Rows.Add(dr);
            }

            var result = _smartCallingUipc.StartDialer(
                dtAgents, 
                dtAccounts, 
                Authentication.UserInfo.Id, 
                bandwidth, 
                maxWaitingTime.Convert<int>(),
                useFct.ToLower() == "true");

            return Json(new { Result = result ? "Success" : "Error" });
        }

        [HttpPost]
        [AuthorizeMember(Rules = "CreateDialer")]
        public ActionResult GetCurrentDialerStatus()
        {
            return Json(new { Result = _smartCallingUipc.GetCurrentDialerStatus() });
        }

        [HttpGet]
        [AuthorizeMember(Rules = "ViewDialerAgentList")]
        public ActionResult DialerAgentList()
        {
            var model = _smartCallingUipc.GetDialerAgentList();
            return View(model);
        }

        [AuthorizeMember(Rules = "InsertDialerAgentList")]
        public ActionResult AddDialerAgentList(string agentName)
        {
            _smartCallingUipc.RemoveAgentFromDialerList(agentName, Authentication.UserInfo.Id);
            return RedirectToAction("DialerAgentList");
        }

        [AuthorizeMember(Rules = "ViewDialerList")]

Efes.Backoffice/Views/SmartCalling/ByCapitalGroup.cshtml
@model Efes.Models.SmartCalling.ByCapitalGroupModel
@{
    ViewBag.Title = "Akıllı Arama";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-blue-sharp sbold">
                        Anapara Grubuna Göre Dosyalarım
                    </span>
                </div>
                <div class="actions">
                    @if (Model.ByCapitalGroupList.Any())
                    {
                        <div class="row">
                            <div class="col-md-6">
                                <select id="ddlFakePhoneList" class="form-control select2" style="width: 150px;">
                                    <option value="">Dahili</option>
                                    @if (Model.FakeNumbers.Any())
                                    {
                                        foreach (var phone in Model.FakeNumbers)
                                        {
                                            if (!string.IsNullOrWhiteSpace(phone.Number) && (phone.Number.Length >= 10))
                                            {
                                                <option value="@phone.Number.Trim()">@(phone.Number.Trim().Substring(0, 3) + " " + phone.Number.Trim().Substring(3, 3) + " " + phone.Number.Trim().Substring(6, 2) + " " + phone.Number.Trim().Substring(8, 2))</option>
                                            }
                                        }
                                    }
                                </select>
                            </div>
                            <div class="col-md-6">
                                <a href="javascript:;" class="btn green call" onclick="SmartCalling.CallAll()">
                                    <i class="fa fa-phone"></i> Tümünü Ara
                                </a>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="portlet-body">
                @if (Model.DebtGroups.Any())
                {
                    using (Html.BeginForm("ByCapitalGroup", "SmartCalling", FormMethod.Get))
                    {
                        <div class="row">
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <label>Anapara Grubu</label>
                                <select id="ddlDebtGroup" name="debtGroupType" class="form-control select2" onchange="this.form.submit() ">
                                    @foreach (var item in Model.DebtGroups)
                                    {
                                        <option value="@item.Key" @(Model.SelectedDebtGroup == item.Key ? "selected='selected'" : "")> @item.Value</option>
                                    }
                                    <option value="0" @(Model.SelectedDebtGroup == 0 ? "selected='selected'" : "")> Tümü </option>
                                </select>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-3">
                                <label>Portföy</label>
                                <select id="ddlPortfolio" name="portfolioId" class="form-control select2" onchange="this.form.submit() ">
                                    @foreach (var item in Model.Portfolios)
                                    {
                                        <option value="@item.Id" @(Model.SelectedPortfolio == item.Id ? "selected='selected'" : "")> @item.Name</option>
                                    }
                                    <option value="0" @(Model.SelectedPortfolio == 0 ? "selected='selected'" : "")> Tümü </option>
                                </select>

                            </div>
                        </div>
                    }
                }
                <div class="margin-bottom-10"></div>
                @if (Model.ByCapitalGroupList.Any())
                {

                    <table class="table table-striped table-bordered table-hover tablePager">
                        <thead>
                            <tr>
                                <th><input type="checkbox" id="chcSelectAll"></th>
                                <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1"> Account Id </th>
                                <th> Ad Soyad </th>
                                <th> Portföy </th>
                                <th> Anapara</th>
                                <th> Toplam Risk </th>
                                <th> İşlemler </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ByCapitalGroupList)
                            {
                                <tr class="@(item.IsCalledToday ? "success" : "")">

                                    <td>
                                        @if (!string.IsNullOrWhiteSpace(item.PhoneNumber))
                                        {
                                            <input type="checkbox" data-phone="@item.PhoneNumber" data-name="@item.Name" data-type="phone">
                                        }
                                    </td>
                                    <td><a href="/Obligor/Detail?accountId=@item.AccountId">@item.AccountId</a> </td>
                                    <td>@item.Name</td>
                                    <td>@item.Portfolio</td>
                                    <td>@item.DebtPrinciple</td>
                                    <td>@item.TotalDebtAmount</td>
                                    <td class="call">
                                        @if (!string.IsNullOrWhiteSpace(item.PhoneNumber))
                                        {
                                            <a href="javascript:SmartCalling.CallOne('@item.PhoneNumber.Trim()', '', '@item.Name', '@item.AccountId')" class="btn blue @(item.IsCalledToday ? "red-stripe" : "")">
                                                <i class="fa fa-phone"></i> Ara
                                            </a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-info">
                        <strong>Bilgi: </strong> Dosya bulunamamıştır.
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section PageScripts{
    <script src="/Content/scripts/SmarCalling.js"></script>
    <script type="text/javascript">
        SmartCalling.Init();
    </script>
}

Efes.Backoffice/Views/SmartCalling/DialerAgentList.cshtml
@model System.Collections.Generic.List<Efes.Models.SmartCalling.DialerAgent>
<style type="text/css">
    .table-condensed > tbody > tr > td {
        padding: 1px;
    }
</style>

<div class="row">
    <div class="col-md-6">
        <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-blue-sharp sbold">Dialer Agent Listesi</span>
                </div>
               
            </div>
            <div class="portlet-body">
                @if (Model.Any())
                {
                    <table class="table table-striped table-bordered table-hover" id="dialerCallListTable">
                        <thead>
                            <tr>
                                <th> Agent </th>
                                <th> Arama Süresi </th>
                                <th> İşlemler </th>
                            </tr>
                        </thead>
                        <tbody id="tBodyDialerList">
                            @foreach (var dcl in Model)
                            {
                                <tr>
                                    <td>@dcl.AgentName</td>
                                    <td>@dcl.LastCalledDateToString</td>
                                    <td>
                                        <a href="/SmartCalling/AddDialerAgentList?agentName=@dcl.AgentName">
                                            Listeye Ekle
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-info">
                        <strong>Bilgi: </strong> Kayıt bulunamadı.
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Efes.Backoffice/Views/SmartCalling/NewAppointed.cshtml
@model Efes.Models.SmartCalling.NewAppointedModel
@{
    ViewBag.Title = "Akıllı Arama";
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-blue-sharp sbold">
                        Yeni Atanan Dosyalarım
                    </span>
                </div>
                <div class="actions">
                    @if (Model.NewAppointedList.Any())
                    {
                        <div class="row">
                            <div class="col-md-6">
                                <select id="ddlFakePhoneList" class="form-control select2" style="width: 150px;">
                                    <option value="">Dahili</option>
                                    @if (Model.FakeNumbers.Any())
                                    {
                                        foreach (var phone in Model.FakeNumbers)
                                        {
                                            if (!string.IsNullOrWhiteSpace(phone.Number) && (phone.Number.Length >= 10))
                                            {
                                                <option value="@phone.Number.Trim()">@(phone.Number.Trim().Substring(0, 3) + " " + phone.Number.Trim().Substring(3, 3) + " " + phone.Number.Trim().Substring(6, 2) + " " + phone.Number.Trim().Substring(8, 2))</option>
                                            }
                                        }
                                    }
                                </select>
                            </div>
                            <div class="col-md-6">
                                <a href="javascript:;" class="btn green call" onclick="SmartCalling.CallAll()">
                                    <i class="fa fa-phone"></i> Tümünü Ara
                                </a>
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="portlet-body">

                @if (Model.NewAppointedList.Any())
                {
                    <div class="clearfix">
                        <div class="btn-group btn-group btn-group-justified">
                            <a href="@Url.Action("NewAppointed", "SmartCalling", new {type = "0"})" class="btn red"> Günlük </a>
                            <a href="@Url.Action("NewAppointed", "SmartCalling", new {type = "1"})" class="btn blue"> Haftalık </a>
                            <a href="@Url.Action("NewAppointed", "SmartCalling", new {type = "2"})" class="btn green"> Aylık </a>
                            <a href="@Url.Action("NewAppointed", "SmartCalling", new {type = "3"})" class="btn yellow-saffron"> Tümü </a>
                        </div>
                    </div>
                    <div class="clearfix margin-bottom-30"> </div>
                    <div class="clearfix">
                        <table class="table table-striped table-bordered table-hover tablePager">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" id="chcSelectAll"></th>
                                    <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1"> Account Id </th>
                                    <th> Ad Soyad </th>
                                    <th> Atama Tarihi </th>
                                    <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1"> Dosya Sahibi </th>
                                    <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1"> Portföy </th>
                                    <th class="col-lg-1 col-md-1 col-sm-1 col-xs-1"> Toplam Risk </th>
                                    <th> Anapara </th>
                                    <th> İşlemler </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.NewAppointedList)
                                {
                                    <tr class="@(item.IsCalledToday ? "success" : "")">
                                        <td>
                                            @if (!string.IsNullOrWhiteSpace(item.Phone))
                                            {
                                                <input type="checkbox" data-phone="@item.Phone" data-name="@item.AdSoyad" data-accountid="@item.AccountId" data-type="phone">
                                            }
                                        </td>
                                        <td><a href="/Obligor/Detail?accountId=@item.AccountId">@item.AccountId</a> </td>
                                        <td>@item.AdSoyad</td>
                                        <td>@item.AtamaTarihi</td>
                                        <td>@item.DosyaSahibi</td>
                                        <td>@item.Portfoy</td>
                                        <td>@item.ToplamRisk</td>
                                        <td>@item.Anapara</td>
                                        <td class="call">
                                            @if (!string.IsNullOrWhiteSpace(item.Phone))
                                            {
                                                <a href="javascript:SmartCalling.CallOne('@item.Phone.Trim()', '', '@item.AdSoyad')" class="btn blue  @(item.IsCalledToday ? "red-stripe" : "")">
                                                    <i class="fa fa-phone"></i> Ara
                                                </a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                }
                else
                {
                    <div class="alert alert-info">
                        <strong>Bilgi: </strong> Dosya bulunamamıştır.
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Efes.Backoffice/Views/SmartCalling/Reminder.cshtml
@model  List<Efes.Models.Obligor.ReminderModel>
@{
    ViewBag.Title = "Hatırlatmalar";
}


<div class="row">
    <div class="col-md-12">
        <div class="portlet light portlet-fit bordered">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject font-blue-sharp sbold">
                        Hatırlatma Listesi
                    </span>
                </div>
                <div class="actions pull-left">

                </div>
            </div>
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-12">
                        @using (Html.BeginForm("Reminder", "SmartCalling", FormMethod.Get))
                        {
                            <label class="control-label" for="txtAdvancePaymentDate" style="font-weight: bold;">Hatırlatıcı Tarihi:</label>

                            <div class="input-group input-small date date-picker txtAdvancePaymentDate"
                                 data-date-format="dd-mm-yyyy"
                                 data-date-end-date="">
                                <input type="text" class="form-control" readonly="" value="@(ViewBag.Date)" id="txtDate" name="date" onchange="this.form.submit()">
                                <span class="input-group-btn">
                                    <button class="btn default" type="button">
                                        <i class="fa fa-calendar"></i>
                                    </button>
                                </span>
                            </div>
                        }
                    </div>
                </div>
                <div class="margin-bottom-10"></div>
                @if (Model.Any())
                {
                    <table class="table table-striped table-bordered table-hover tablePager">
                        <thead>
                            <tr>
                                <th> Account Id </th>
                                <th> Tipi </th>
                                <th> Detay </th>
                                <th> Kullanıcı </th>
                                <th> Hatırlatma Tarihi </th>
                                <th> Oluşturulma Tarihi </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td><a href="/Obligor/Detail?accountId=@item.AccountId">@item.AccountId</a></td>
                                    <td>@item.TypeName</td>
                                    <td>@item.Detail</td>
                                    <td>@item.Username</td>
                                    <td>@item.RemindDate.ToString("dd MMMM yyyy hh:mm")</td>
                                    <td>@item.CreatedDate.ToString("dd MMMM yyyy hh:mm")</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
                else
                {
                    <div class="alert alert-info">
                        <strong>Bilgi: </strong> Dosya bulunamamıştır.
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section PageScripts{

    <script type="text/javascript">
        $(function () {
            $(".tablePager").dataTable($.extend(CommonDataTablesSettings, { "order": [[3, "asc"]], "pageLength": -1 }));
        });
    </script>
}