Efes.Backoffice/Controllers/LawOfficeController.cs
using Efes.Models.Law;
using Efes.UIPC;
using Efes.WC;
using System.Web.Mvc;

namespace Efes.Backoffice.Controllers
{
    public class LawOfficeController : BaseController
    {
        private readonly LawOfficeUipc _lawOfficeUipc;
        private readonly LocationUipc _locationUipc;
        public LawOfficeController()
        {
            _lawOfficeUipc = new LawOfficeUipc();
            _locationUipc = new LocationUipc();
        }
        // GET: LawOffice
        [AuthorizeMember(Rules = "ViewOfficeList")]
        public ActionResult Index()
        {
            var model = _lawOfficeUipc.GetLawOfficeModelList(Authentication.UserInfo.Id);
            return View(model);
        }

        // GET: LawOffice/Details/5
        [AuthorizeMember(Rules = "ViewOfficeDetails")]
        public ActionResult Details(int id)
        {
            var model = _lawOfficeUipc.GetLawOfficeById(id);
            return View(model);
        }

        // GET: LawOffice/Create
        [AuthorizeMember(Rules = "CreateOffice")]
        public ActionResult Create()
        {
            var model = new OfficeModel();
            model.CityList = _locationUipc.GetCities();
            return View(model);
        }

        // POST: LawOffice/Create
        [HttpPost]
        [AuthorizeMember(Rules = "CreateOffice")]
        public ActionResult Create(OfficeModel officeModel)
        {
            try
            {
                var success = _lawOfficeUipc.CreateLawOffice(officeModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LawOffice/Edit/5
        [AuthorizeMember(Rules = "EditOffice")]
        public ActionResult Edit(int id)
        {
            var model = _lawOfficeUipc.GetLawOfficeById(id);
            model.CityList = _locationUipc.GetCities();
            return View(model);
        }

        // POST: LawOffice/Edit/5
        [HttpPost]
        [AuthorizeMember(Rules = "EditOffice")]
        public ActionResult Edit(int id, OfficeModel officeModel)
        {
            try
            {
                var success = _lawOfficeUipc.UpdateLawOffice(officeModel);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: LawOffice/Delete/5
        [AuthorizeMember(Rules = "DeleteOffice")]
        public ActionResult Delete(int id)
        {
            var model = _lawOfficeUipc.GetLawOfficeById(id);
            return View(model);
        }

        // POST: LawOffice/Delete/5
        [HttpPost]
        [AuthorizeMember(Rules = "DeleteOffice")]
        public ActionResult Delete(int id, OfficeModel officeModel)
        {
            try
            {
                officeModel.IsActive = false;
                var success = _lawOfficeUipc.UpdateLawOffice(officeModel);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        
    }
}

Efes.Backoffice/Controllers/LawOfficeUserController.cs
using Efes.Entities.LawOffice;
using Efes.UIPC;
using Efes.Utility;
using Efes.WC;
using System.Web.Mvc;

namespace Efes.Backoffice.Controllers
{
    public class LawOfficeUserController : BaseController
    {
        private readonly LawOfficeUserUipc _lawOfficeUserUipc;
        public LawOfficeUserController()
        {
            _lawOfficeUserUipc = new LawOfficeUserUipc();
        }

        [HttpGet]
        [AuthorizeMember(Rules = "ViewLawOfficeUser")]
        public ActionResult Index(int id)
        {
            var model = _lawOfficeUserUipc.GetOfficeUserAssignmentModel(id);
            return View(model);
        }

        [AuthorizeMember(Rules = "UpdateLawOfficeUser")]
        public JsonResult InsertOrUpdateLawOfficeUser(string userId, string lawOfficeId, bool assigned)
        {
            var officeUser = new OfficeUser()
            {
                UserId = userId.Convert<int>(),
                LawOfficeId = lawOfficeId.Convert<int>(),
                IsActive = true
            };
            var result = _lawOfficeUserUipc.InsertOrUpdateLawOfficeUser(officeUser, Authentication.UserInfo.Id, assigned);
            return Json(new { Result = result ? "Success" : "Error" });
        }

    }
}

Efes.Backoffice/Views/LawOfficeUser/Index.cshtml
@using Efes.WC
@model   Efes.Models.Law.OfficeUserAssignmentModel

@{
    ViewBag.Title = "Hukuk Bürosu Kullanıcı Yönetimi";
}

@if (Authentication.IsAllowedToSee("ViewLawOfficeUser") && Authentication.IsAllowedToSee("UpdateLawOfficeUser"))
{
    <style>
        .ms-container {
            width: 810px !important;
        }

            .ms-container .ms-list {
                height: 600px !important;
            }
    </style>
    <link href="/assets/global/plugins/bootstrap-select/css/bootstrap-select.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/global/plugins/jquery-multi-select/css/multi-select.css" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/select2")
    <div class="row">
        <div class="col-md-12">
            <div class="portlet light form-fit bordered">
                <div class="portlet-title">
                    <div class="caption">
                        <span class="caption-subject font-blue-chambray bold uppercase">Hukuk Bürosuna Kullanıcı Atama</span>
                    </div>
                </div>
                <div class="portlet-body form">
                    <form class="form-horizontal form-row-seperated">
                        <div class="form-body">
                            <div class="form-group">
                                <label class="control-label col-md-3">@Model.OfficeName</label>
                                <div class="col-md-9">
                                    <input type="hidden" name="lawOfficeId" id="lawOfficeId" value="@Model.OfficeId" />
                                    <select multiple="multiple" class="multi-select" id="multiSelectAllUsers" name="multiSelectAllUsers" style="display: none">
                                        @foreach (var user in Model.AllUsers)
                                        {
                                            <option value="@user.Id" @(Model.OfficeUsers.Any(c => c.Id == user.Id) ? "selected" : "")>
                                                @user.Name
                                            </option>
                                        }

                                    </select>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <p>
        @Html.ActionLink("Listeye Geri Dön", "Index", "LawOffice")
    </p>

    @section PageScripts{
        @Scripts.Render("~/bundles/select2")
        @Scripts.Render("~/bundles/multi-select")
        <script type="text/javascript">
        $("#multiSelectAllUsers").multiSelect({

            selectableHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Ara'>",
            selectionHeader: "<input type='text' class='search-input form-control' autocomplete='off' placeholder='Ara'> ",
            afterInit: function (ms) {
                var that = this,
                    $selectableSearch = that.$selectableUl.prev(),
                    $selectionSearch = that.$selectionUl.prev(),
                    selectableSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selectable:not(.ms-selected)',
                    selectionSearchString = '#' + that.$container.attr('id') + ' .ms-elem-selection.ms-selected';

                that.qs1 = $selectableSearch.quicksearch(selectableSearchString)
                .on('keydown', function (e) {
                    if (e.which === 40) {
                        that.$selectableUl.focus();
                        return false;
                    }
                });

                that.qs2 = $selectionSearch.quicksearch(selectionSearchString)
                .on('keydown', function (e) {
                    if (e.which == 40) {
                        that.$selectionUl.focus();
                        return false;
                    }
                });
            },

            afterSelect: function (values) {
                App.blockUI({
                    target: ".form-group",
                    boxed: true
                });
                Core.AjaxCall({
                    url: "/LawOfficeUser/InsertOrUpdateLawOfficeUser",
                    data: JSON.stringify({ userId: parseInt(values[0]), lawOfficeId: parseInt($('#lawOfficeId').val()), assigned: true }),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        App.unblockUI(".form-group");

                        if (data.Result === "Success") {

                        } else if (data.Result === "Error") {

                        }
                    }
                });
            },
            afterDeselect: function (values) {
                App.blockUI({
                    target: ".form-group",
                    boxed: true
                });
                Core.AjaxCall({
                    url: "/LawOfficeUser/InsertOrUpdateLawOfficeUser",
                    data: JSON.stringify({ userId: parseInt(values[0]), lawOfficeId: parseInt($('#lawOfficeId').val()), assigned: false }),
                    dataType: "json",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        App.unblockUI(".form-group");

                        if (data.Result === "Success") {

                        } else if (data.Result === "Error") {

                        }
                    }
                });
            }
        });

        $(".ms-selectable").prepend("<div class='bg-blue-chambray bg-font-blue-chambray' style='padding: 5px;'> Bütün Kullanıcılar </div>");
        $(".ms-selection").prepend("<div class='bg-blue-chambray bg-font-blue-chambray' style='padding: 5px;'> Büronun Kullanıcıları </div>");

        $("#multiSelectAllUsers").show();
        </script>
    }
}